{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-basetheme
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/basetheme_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/basetheme/basetheme_{{ version }}.tar.gz
  sha256: 1fd1df5ac47ca7237c5d314f4255387d08e5cb4b62afad1318f423646ad42d3c

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('basetheme')"           # [not win]
    - "\"%R%\" -e \"library('basetheme')\""  # [win]

about:
  home: https://github.com/KKPMW/basetheme
  license: GPL-2.0-only
  summary: 'Functions to create and select graphical themes for the base plotting system. Contains: 1) several custom pre-made themes 2) mechanism for creating new themes by making persistent changes to the graphical parameters of base plots.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: basetheme
# Title: Themes for Base Graphics Plots
# Version: 0.1.2
# Authors@R: person("Karolis", "Koncevicius", email = "karolis.koncevicius@gmail.com", role = c("aut", "cre"))
# Maintainer: Karolis Koncevicius <karolis.koncevicius@gmail.com>
# Description: Functions to create and select graphical themes for the base plotting system. Contains: 1) several custom pre-made themes 2) mechanism for creating new themes by making persistent changes to the graphical parameters of base plots.
# Depends: R (>= 3.2.2)
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/KKPMW/basetheme
# BugReports: https://github.com/KKPMW/basetheme/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-17 17:47:10 UTC; karolis
# Author: Karolis Koncevicius [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-10-17 19:00:06 UTC
